name: Build Docker Images (Frontend)

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    uses: multi-repo/workflows/.github/workflows/kaniko-build.yaml@main
    with:
      image-name: ${{ github.repository }}/app
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      NEXT_PUBLIC_LOCAL_API_URL: '${{ secrets.NEXT_PUBLIC_LOCAL_API_URL }}'
      NEXT_PUBLIC_AFISHA_API_URL: '${{ secrets.NEXT_PUBLIC_AFISHA_API_URL }}'
      NEXT_PUBLIC_IMAGES_HOSTNAME: '${{ secrets.NEXT_PUBLIC_IMAGES_HOSTNAME }}'
      NEXT_PUBLIC_TICKET_MANAGER_SCRIPT_URL: '${{ secrets.NEXT_PUBLIC_TICKET_MANAGER_SCRIPT_URL }}'
      NEXT_PUBLIC_TICKET_MANAGER_WIDGET_ID: '${{ secrets.NEXT_PUBLIC_TICKET_MANAGER_WIDGET_ID }}'

  trigger-cleanup:
    needs: [trigger-build]
    uses: multi-repo/workflows/.github/workflows/clean-registry.yaml@main
    with:
      owner: ${{ github.repository_owner }}
      repository: frontend
      package: frontend/app
      keep_n_tagged: 2
      dry_run: true
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    needs: [trigger-cleanup]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying application"
